# Site settings
title: Haryo Sukmawanto
email: Haryo@Sukmawanto.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: Fragrag
github_username:  Fragrag

# Plugins
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown

highlighter: none

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/
  articles:
    output: true
    permalink: /articles/:path/


